# Generated by Django 3.2.7 on 2021-09-16 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
