# Generated by Django 3.2.7 on 2021-09-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='timestamp',
        ),
    ]
